### ISSUE TITLE
$resource cache and 3.0.0-beta-x

### ISSUE THREAD

**Issue by whitehat101** [jmdobry/angular-cache#112]
I was able to use a custom LocalStorage cache with 3.0 and angular 1.2.16, but when I tried to pass a cache to a $http via the `cache:` option, I got the following exception:

```
TypeError: undefined is not a function
    at Object.get (http://127.0.0.1:3000/assets/angular-cache-3.0.0-beta.2.js?body=1:364:33)
    at sendReq (http://127.0.0.1:3000/assets/angular.js?body=1:8159:28)
    at $http.serverRequest (http://127.0.0.1:3000/assets/angular.js?body=1:7922:16)
    at wrappedCallback (http://127.0.0.1:3000/assets/angular.js?body=1:11320:81)
```

``` javascript
    var item;

    if (this.$$storage) {
        // following line, chrome put the cursor after $$storage.
        var itemJson = this.$$storage.getItem(this.$$prefix + '.data.' + key); 

        if (itemJson) {
            item = angular.fromJson(itemJson);
        } else {
            return;
        }
```

I tried with all the betas, and they all errored at the same location. Downgrading to 2.3.3 worked (after changing the module names) without changing config.

`localStorage` and `sessionStorage` caused exceptions. Omitting `storageMode` worked with the betas.

``` coffeescript
  versionCache = DSCacheFactory 'versionCache',
    storageMode: 'localStorage'
    capacity: 1024
```

**Comment by jmdobry** [comment]
ngResource is now officially support in [4.1.0](https://github.com/jmdobry/angular-cache/releases/tag/4.1.0)

**Comment by whitehat101** [comment]
:+1: Nice! I'll definitely keep your packages in mind with my next angular project.
