### ISSUE TITLE
Error using DSCacheFactory with $http/ $resource and localStorage

### ISSUE THREAD

**Issue by gjspaho** [jmdobry/angular-cache#122]
Following the second scenario on the following guide link [Angular-cache w/$http](http://angular-data.pseudobry.com/documentation/guide/angular-cache/http), if you set `storageMode: localStorage` you get the following error: 

> TypeError: undefined is not a function
>     at Object.get (http://localhost:52554/scripts/lib/angular-cache.js:363:35)

It seems `this.$$storage.getItem` is undefined.
If you remove the localStorage option it works as expected.

**Comment by jmdobry** [comment]
ngResource is now officially support in [4.1.0](https://github.com/jmdobry/angular-cache/releases/tag/4.1.0)
