### ISSUE TITLE
Feature request : Promise API for get/put/remove

### ISSUE THREAD

**Issue by rvenugopal** [jmdobry/angular-cache#123]
Hullo

Thanks for creating this wonderful library.

Would it be possible to create a promise API for the accessor calls?  I wrap most of my API calls inside services (which return promises since $http returns a promise).  So there is some friction as your library does not return a promise.  Please let me know if there is a way around this.  I was hoping for something along the lines of what I posted down below. 

Thanks
-Rv

````js

/*** Sample implementation suggestion ***/
function serviceFn(url, cacheKey) {

/// Return data from cache if available
/// Return data from server

profileCache.find(cacheKey)
     .then(function(data) {
            return data.result;
      }.then(function(data) {
            if (typeof(data) == 'undefined' {
                 /// Make http call here and then return the appropriate promise
            }

      } 

}


```

**Comment by jmdobry** [comment]
I'll just leave this here as an example of how to do it.
