### ISSUE TITLE
2.3.7 - onExpire isn't called during: _loadCacheConfig

### ISSUE THREAD

**Issue by intellix** [jmdobry/angular-cache#125]
Hey, so I set a default maxAge really low (10 sec) for an item to do some testing and debug why my onExpire wasn't getting called.

My default config: 
```js
// optionally set cache defaults
$angularCacheFactoryProvider.setCacheDefaults({
    capacity: 1000,
    maxAge: 10 * 1000,
    deleteOnExpire: 'aggressive',
    recycleFreq: 20 * 1000,
    storageMode: 'localStorage',
    //storageImpl: myLocalStoragePolyfill,
    verifyIntegrity: true
});
```

When I do a page refresh after 10 seconds (cache item has expired), during `_loadCacheConfig` the keys are looped through and deleted if they've expired but `onExpires()` isn't called. I feel like it should, I don't think the flow should be different just because the check was made on page-refresh rather than during the `flush()`.

What do you think?

**Comment by demisx** [comment]
+1

**Comment by jmdobry** [comment]
2.x shouldn't be used after 4.x is released
