### ISSUE TITLE
module "../utils" not found for bower package 3.1.1

### ISSUE THREAD

**Issue by joshgerdes** [jmdobry/angular-cache#134]
Error: module "../utils" not found

In the bower package for 3.1.1 it looks like there is a reference to utils module but the code in the util folder was not provided in the bower package.  When you get a chance can you please update the bower package. Thanks!

**Comment by jaworskm** [comment]
In the `dist/angular-cache.js` file see line 230

```js
var utils = require('../utils');
```

**Comment by jmdobry** [comment]
Works for me. I'm not sure how to reproduce this issue.

![screen shot 2015-03-17 at 9 28 14 am](https://cloud.githubusercontent.com/assets/1213510/6690766/03c452e6-cc88-11e4-9f05-f8fe32a83877.png)

**Comment by joshgerdes** [comment]
I haven't tested this lately but when I was using the bower package manager (not npm) to install the bower package I came across the relative pathing issue. It was in October, but if I recall the npm package worked correctly when I tested it.

**Comment by jmdobry** [comment]
Should be fixed in 4.0.0
