### ISSUE TITLE
angular-cache with cordova

### ISSUE THREAD

**Issue by ahmedmrj** [jmdobry/angular-cache#137]
First of all , thank you very much for this plugin. does angular-cache work with cordova? I have built an application that work fine in desktop browser but in mobile emulator DSCacheFactory can't be instantiated.

**Comment by evanjmg** [comment]
Any update on this?

**Comment by charyorde** [comment]
Using `"angular-cache": "^4.6.0"`, `localStorage` works fine on `1.7.16`. SessionStore does not work. With sessionstore it reverts to memory as mentioned by @jmdobry
