### ISSUE TITLE
Angular cache 3.x documentation link in README

### ISSUE THREAD

**Issue by demisx** [jmdobry/angular-cache#156]
My understanding that JS-Data replaces Angular Data 1.x The link in README for angular-cache 3.x takes you to the site that talks about angular-data 1.x. This may confuse a lot of people. Maybe the link should take to the Angular-cache dedicated page? http://angular-data.pseudobry.com/documentation/api/angular-cache/angular-cache

**Comment by jmdobry** [comment]
Angular-data 2.x (now js-data-angular used in conjunction with js-data) has no use for Angular-cache whatsoever, as JSData has its own cache expiry capabilities. That's not to say JSData and Angular-cache are mutually exclusive, you can use one or the other, or both, they don't care.

Angular-cache is only relevant to Angular-data 1.x, therefore the link _should_ be to Angular-data 1.x, and Angular-data 1.x only. I could however update the wording around the link to be more specific on this point.

**Comment by demisx** [comment]
Thank you for clarifying it. It is a little confusing with all these different versions floating in the docs around. :) 

I am currently using Angular-data 2.1 and I love it. Now, I have a need to create a small cache where I can store some UI related data. It has nothing to do with models or persistence layer. Should I not use `angular-cache` at all and instead inject items to the data store directly? If you could please point me out in the right direction, I would highly appreciate it. Thank you.

**Comment by jmdobry** [comment]
My answer would be the same as when you asked this [here](https://groups.io/org/groupsio/jsdata/thread/angular_cache/26953?threado=0)

**Comment by demisx** [comment]
I thought this sounded familiar. Sorry, been reading tons of material lately. Start forgetting things :)
