### ISSUE TITLE
$http Cache seems to be caching all requests.

### ISSUE THREAD

**Issue by jarzuaga** [jmdobry/angular-cache#159]
I'm setting up my cache like this:

    DSCacheFactory("defaultCache", {
        storageMode: "localStorage",
        maxAge: 3600000, // time in milliseconds
        deleteOnExpire: "aggressive"
    });

    $http.defaults.cache = DSCacheFactory.get('defaultCache');

My expectation was that for $http requests where I set the cache property to true, the cache would be enabled. It seems like the opposite is true. All requests are cached except those where I set the cache property false. Could I get some clarification on this?

**Comment by jmdobry** [comment]
Sure, regardless of what it says in Angular's documentation, you can see in the [source code](https://github.com/angular/angular.js/blob/master/src/ng/http.js#L1037) for `$http` that if you set `$http.defaults.cache` and you _don't explicitly set `config.cache` to `false`_ for a given request, it will cache the request.

Angular-cache has absolutely zero control over when `$http` decides to cache a request. You'll either want to open an issue with Angular to fix their documentation, or to fix the code to match the behavior described in the docs.
