### ISSUE TITLE
onExpire is still called when cache is empty

### ISSUE THREAD

**Issue by demisx** [jmdobry/angular-cache#164]
Hi. I am using the latest 4.0.1 version. I have cache created as:

```js
 var authCache = CacheFactory('authCache', {
      maxAge: ...,
      deleteOnExpire: 'aggressive',
      storageMode: 'localStorage',
      onExpire: function (key, value) { // <- still fires for the removed item
        switch(key) {
          case 'authToken':
            $http.get(globalConfig.apiBase + '/auth/rt', {
              headers: {
                'X-Auth-Token': value
              }
            })
              .success(function (data) {
                authCache.put(key, data.token);
              })
              .error(function (data) {
                authService.logOut();
              });
            break;
        }
      }
```

As expected, the `onExpire` kicks in when the added `authToken` has expired. However, if I remove the `authToken` key from this cache, the `onExpire` continues to fire with the `key` param set to removed item and the `value` set to null, even if this cache contains no such item. Shouldn't be `onExpire` auto-disabled if the cache contains 0 items? Thank you.

**Comment by jmdobry** [comment]
Can you describe _exactly_ the behavior you're seeing? Is the onExpire being called right when you remove the item? Can you verify that `authCache.keys().length === 0` after the items expire? Where else might you be adding items to the cache?

**Comment by demisx** [comment]
Yeah, the length is 0 after the key is removed. Everything appears normal, no red flags. I've made a plunker to demo the issue (below). You'll see that after clicking the button, the auth token appears to be removed, but then 10 sec later, onExpire is still trying to renew it.

http://plnkr.co/edit/hriQr3iGrV3uCxEpKasO?p=preview

Let me know if you need anything else.

**Comment by jmdobry** [comment]
Thanks, I will debug.

**Comment by jmdobry** [comment]
Fixed in 4.0.2. @demisx Thanks for the plunker demonstrating the issue, it sure makes debugger faster and easier.

**Comment by demisx** [comment]
:+1: Thank you for prompt resolution! `js-data` rocks!

**Comment by jmdobry** [comment]
Thanks! (Though this is the angular-cache project...)

**Comment by demisx** [comment]
Yeah, I use them both and they are equally great! :)
