### ISSUE TITLE
CacheFactory.destroy(cacheId)

### ISSUE THREAD

**Issue by butchewing** [jmdobry/angular-cache#168]
`CacheFactory.destroy(cacheId)` does not appear to be removing the cache with the given cacheId.

**Comment by jmdobry** [comment]
[Here is a plunker](http://plnkr.co/edit/21MRvd?p=preview) that demonstrates a cache being destroyed via `CacheFactory#destroy(cacheId)`.

Perhaps you could use the plunker to reproduce the issue.

**Comment by butchewing** [comment]
Oh, I misunderstood what the `cacheId` was. I was trying to destroy the data using a cache key.
 
`CacheFactory.destroy(cacheId)` works as expected. Where `cacheId` is the ID of the CacheFactory.

In the following code block the `cacheId` is `'newCache'`
`CacheFactory('newCache');`
