### ISSUE TITLE
Problem while using angulat-cache with Require.js

### ISSUE THREAD

**Issue by edr999** [jmdobry/angular-cache#172]
Hi
I added angular-cache (4.1.0) to be loaded by require.js
the angular-cache module request angular from the root folder http://localhost/mysite/angular.js (although angular is already loaded from another location) and gets 404 for that reqest

thanks
edr999

**Comment by jmdobry** [comment]
In order for me to help you, you're going to have to give me more information than "it didn't work".

- good - Your versions of Angular, Angular-cache, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

**Comment by edr999** [comment]
thanks.
I created plnkr http://plnkr.co/edit/vQbWKKHPtk2RnolWLyE9?p=info
i'm using angular ver 1.3.15
using previous versions all is OK (on the demo it is Angular-cache 3) but when i'm using the angular-cache 4.1 i'm getting an error that the angular cache is trying to call angular.js from other place and get 404
thanks so much for the help

**Comment by jmdobry** [comment]
Here's a forked version of your plunker that shows how to setup your requirejs `paths` configuration correctly: http://plnkr.co/edit/GvvqJA?p=preview

**Comment by edr999** [comment]
Thanks so much
it is working!
The missing part was the shim configuration on the require
Issue closed
