### ISSUE TITLE
capacity does not work on often reload

### ISSUE THREAD

**Issue by Delagen** [jmdobry/angular-cache#179]
capacity setted to 10
cache.keys().length = 135

on every page reload it requests resource and put into cache
this code does not work because $$lruHeap.size() equals to 1
```
 if ($$lruHeap.size() > this.$$capacity) {
	            this.remove($$lruHeap.peek().key);
	          }
```
so capacity does not remove old items if they does not expire

**Comment by jmdobry** [comment]
What does `often reload` mean?

**Comment by Delagen** [comment]
Page reload. So every time cache initialized again.

**Comment by jmdobry** [comment]
I need to see your entire cache configuration. Code examples please. Version please. Even better, a plunker that demonstrates the issue. Details!

**Comment by Delagen** [comment]
capacity:10
maxAge: week
storageMode:localstorage

on every page load http get: request?random puts on the cache

so if i make 1000 loads it make 1000 entries in localstorage

**Comment by jmdobry** [comment]
Could you please fork this plunker and demonstrate the issue? http://plnkr.co/edit/RXWGpYqRAfKPS6R38MXs?p=preview

**Comment by Delagen** [comment]
Refresh result and see as keys count exceed capacity
http://plnkr.co/edit/6zyAvLYTDeHJSbCvUllF?p=preview

**Comment by jmdobry** [comment]
Indeed it does.

**Comment by jmdobry** [comment]
Can you try 4.4.0 and see if it works better?

**Comment by Delagen** [comment]
You can try the same plunker. Result the same.
