### ISSUE TITLE
LocalStorage not emptied on clearall/destroyall

### ISSUE THREAD

**Issue by willyboy** [jmdobry/angular-cache#184]
Cache data in local storage is not cleared when clear/destroy all calls are made.

**Comment by jmdobry** [comment]
Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:

- good - Your versions of Angular, Angular-cache, etc, relevant console logs/error, code examples that revealed the issue
- better - A plnkr, fiddle, or bin that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the mailing list.

**Comment by willyboy** [comment]
http://stackoverflow.com/questions/30624026/angular-cache-doesnt-clear-local-storage-cache-when-using-dscachefactory-destro/30624027#30624027

Version is 3.2.5 so I haven't upgraded yet because I haven't been able to review if there are any breaking changes. 

My storage code is: 
if(!DSCacheFactory.get(this.source)){
        DSCacheFactory(this.source);
      }
      var cache = {cache:DSCacheFactory.get(this.source)};
    }
    var that = this;
    $http.get(this.source,cache)
}

I've also noticed that on first page load, DSCacheFactory.get(this.source) is empty even if it exists in localStorage but DSCacheFactory(this.source) loads the cache from storage. I guess I would expect DSCacheFactory.get(this.source) to check localStorage since in my config I have:

DSCacheFactoryProvider.setCacheDefaults({
    storageMode:"localStorage",
    maxAge: 604800000, //7 days
    deleteOnExpire: "passive" //don't scan for expired items
  });

**Comment by jmdobry** [comment]
plunker demonstrating that it works with 4.2.0: http://plnkr.co/edit/hamvsZ?p=preview

plunker demonstrating that it works with 3.2.5: http://plnkr.co/edit/NiOEes?p=preview

Open the Resources tab in chrome devtools and observe the storage in http://run.plnkr.co

**Comment by willyboy** [comment]
Does anything look inherently wrong in the code I pasted? If not, it could be related to Ionic. Besides the difference of using/not using http, I don't see a difference in the code yet yours clearly works.

**Comment by jmdobry** [comment]
I updated [this plunker](http://plnkr.co/edit/NiOEes?p=preview) to more closely match the code in your example, and it still works. Seems like it's either an issue with ionic or the environment in which your app is running.

You could try 4.x. Here are the [breaking changes](https://github.com/jmdobry/angular-cache/blob/master/CHANGELOG.md#breaking-api-changes) moving from 3.x to 4.x.

**Comment by willyboy** [comment]
Awesome, thanks for the help! If I discover anything about an incompatibility between Ionic and angular-cache I'll post it here just as a reference.

**Comment by jmdobry** [comment]
Cool
