### ISSUE TITLE
Create a cache with new operator

### ISSUE THREAD

**Issue by anasmithiam** [jmdobry/angular-cache#186]
Hello, I've tried to create a cache using new operator. Something like

```js
var myCache = new CacheFactory('myCache', {
    maxAge: 60000,
    // ...
  });
```

**It seems that everything it's ok** but the documentation doesn't use the operator 'new' when calling CacheFactory constructor (neither mentioning it). So, it's correct the use of `new CacheFactory(...)`?

**Comment by jmdobry** [comment]
> So, it's correct the use of new CacheFactory(...)?

No, it's not. Follow the documentation:

```js
var myCache = CacheFactory('myCache', {
  maxAge: 60000,
  // ...
});
```

If jshint doesn't like that, then you can do:
```js
var myCache = CacheFactory.createCache('myCache', {
  maxAge: 60000,
  // ...
});
```
