### ISSUE TITLE
4.3 breaks phantomJS tests

### ISSUE THREAD

**Issue by rlucha** [jmdobry/angular-cache#190]
Updating from 4.2 to 4.3 breaks our karma suite, the following errors appear:

PhantomJS 1.9.8 (Linux 0.0.0) ec-autocomplete-controller encountered a declaration exception FAILED
ReferenceError: Can't find variable: Promise
Error: [$injector:modulerr] Failed to instantiate module undefined due to:
Error: [ng:areq] Argument 'module' is not a function, got undefined

We have switched to ~4.2.0 for now until we can investigate further.

**Comment by rlucha** [comment]
Fast! thank you

**Comment by jmdobry** [comment]
No problem, that was my bad, not anticipating others would have PhantomJS tests.
