### ISSUE TITLE
Individual Item level cache maxAge is not overriding the maxAge of the whole cache

### ISSUE THREAD

**Issue by sriramjothimani** [jmdobry/angular-cache#194]
Hi,

The maxAge property of individual item stored in a cache is not overriding the maxAge of the whole cache. Even though we set specific maxAge for the individual items it tends to set the maxAge of the cache. 

Below is the service we have created. 

appCache.service('appCacheSrc', function (CacheFactory) {

    var frontendCache;

    if(!CacheFactory.get('frontend')){
        frontendCache = CacheFactory('frontend', {
             maxAge: 15 * 60 * 1000 
            ,cacheFlushInterval: 30 * 60 * 1000 
            ,deleteOnExpire: 'aggressive' 
            ,storageMode: 'localStorage' 
        });    

        frontendCache.put('/profiles/34', {
            name: 'John',
            skills: ['programming', 'piano'],
            },{maxAge: 60 * 1000});
         
    }
    console.log(frontendCache.info('/profiles/34'));
    return frontendCache;

});

Please let me know if am doing something wrong.

Thanks,
Sriram

**Comment by jmdobry** [comment]
You can't set maxAge for individual items

**Comment by sriramjothimani** [comment]
Ok so I have to create a separate cache if I need to have a different maxAge ?

**Comment by jmdobry** [comment]
Yes
