### ISSUE TITLE
4.3 storagePrefix is not backwards compatible

### ISSUE THREAD

**Issue by sloops77** [jmdobry/angular-cache#200]
The changes to extract the non-angular code updated the default storage prefix from angular-cache.caches to cachefactory-caches. This was doing my head in for quite a while. 

On sidenote - woohoo issue #200!

**Comment by jmdobry** [comment]
Oops, hmm. I think the fix would be to have angular-cache itself change the default back to what it what, rather than modifying CacheFactory.

**Comment by sloops77** [comment]
Yep that is the way to do it
