### ISSUE TITLE
Internal Cache not reloaded on Reload

### ISSUE THREAD

**Issue by sfabriece** [jmdobry/angular-cache#212]
I have noticed that the internal 'caches' object is not being re-populated based on whether localStorage or whatever the underlying storage has. Put in other words, angular-cache is not picking up existing caches on startup.

**Comment by jmdobry** [comment]
Only data gets reloaded, not the meta information associated with a cache. So you need to run the code that creates a cache every time your app loads, and the cache will possibly load any data that was previously saved under that cache's name

**Comment by ronaldheft** [comment]
I'm seeing the same thing due to #211. I was able to temporarily work around this problem by setting `deleteOnExpire` to `none`.

**Comment by jmdobry** [comment]
Should be working better now: https://plnkr.co/edit/Cc1xT8Ra3PWXQvl2J9zs?p=preview
