### ISSUE TITLE
angular-cache.min.js tries to load the .map from dist/

### ISSUE THREAD

**Issue by youurayy** [jmdobry/angular-cache#215]
angular-cache.min.js tries to load the .map from dist:
https://github.com/jmdobry/angular-cache/blob/master/dist/angular-cache.min.js#L2

which confuses Safari:
![image](https://cloud.githubusercontent.com/assets/588573/13193892/b4b1be06-d789-11e5-9e23-7ce3e6af580f.png)

angular-cache.js is fine.

**Comment by youurayy** [comment]
Actually, angular-cache.js states the .map location twice:
https://github.com/jmdobry/angular-cache/blob/master/dist/angular-cache.js#L1321

and also confuses Safari:
![image](https://cloud.githubusercontent.com/assets/588573/13193916/30a9b108-d78a-11e5-9104-e52bb03526cc.png)

**Comment by jmdobry** [comment]
Fixed by [b491ed83](https://github.com/jmdobry/angular-cache/commit/b491ed8361cd092dd82e59eab0031a2e202900a6)
