### ISSUE TITLE
Build error using Gulp: Unexpected token

### ISSUE THREAD

**Issue by arjenfvellinga** [jmdobry/angular-cache#219]
When I try to use your Angular library in our project we get an error using it. During concatenation and minification, gulp-uglify throws following error:

> Error (gulp-uglify): [...]/frontend/vendor/angular/angular-cache/angular-cache.js: Unexpected token: operator (<)

Do you have an idea what is wrong?

**Comment by jmdobry** [comment]
How about you share your gulp config? And show how you're using angular-cache in your code?

**Comment by arjenfvellinga** [comment]
This is our complete gulp config file: https://github.com/HelloLily/hellolily/blob/develop/gulpfile.js

I think this is the relevant part ([line 224](https://github.com/HelloLily/hellolily/blob/develop/gulpfile.js#L224)):
```
gulp.task('vendor-js', [], function() {
    return gulp.src(config.vendor.js.src)
        .pipe(ifElse(!isProduction, function() {
            return sourcemaps.init();
        }))

        .pipe(cached('vendor-js'))
        .pipe(ifElse(isProduction, uglify))
        .pipe(remember('vendor-js'))

        .pipe(concat(config.vendor.js.fileName))
        .pipe(ifElse(!isProduction, function() {
            return sourcemaps.write('.');
        }))
        .pipe(gulp.dest(config.vendor.buildDir))
        .pipe(ifElse(isWatcher, size))
        .pipe(ifElse(isWatcher, livereload));
});
```
with _config.vendor.js.src_ ([line 75](https://github.com/HelloLily/hellolily/blob/develop/gulpfile.js#L75)) being:
```
    vendor: {
        buildDir: 'lily/static/vendor/',
        js: {
            src: [
                'frontend/vendor/**/*jquery.min.js',
                'frontend/vendor/**/*angular.js',
                'frontend/vendor/**/*.js',
                '!frontend/vendor/**/angular-mocks.js',
                '!frontend/vendor/metronic/assets/global/plugins/ie-fixes/**/*.js',  // IE fixes
            ],
```

The _angular-cache.js_ file is placed _frontend/vendor/angular/angular-cache/_

The gulp-uglify error is given when issuing the (our) _gulp build_ command, so actually before even using you library in code.

**Comment by jmdobry** [comment]
And what's the exact `angular-cache.js` file you're using? Where did you get it?

**Comment by arjenfvellinga** [comment]
I got it from https://github.com/jmdobry/angular-cache/tree/master/dist , stable version 4.5.0.

But I now see I made a mistake (and never gonna make again...), right clicking the link saves a html file named .js instead of the raw js file. So I got the wrong file, sorry for the inconvenience.
