### ISSUE TITLE
Exception when including angular-cache from bower

### ISSUE THREAD

**Issue by smelukov** [jmdobry/angular-cache#220]
```
Uncaught ReferenceError: require is not defined
    webpackUniversalModuleDefinition@angular-cache.js:12
```

**Comment by smelukov** [comment]
I'm using webpack.
angular and angular-cache are including in common chunk

**Comment by jmdobry** [comment]
I'm not sure what to do with this bug report. Can you provide more information so I can easily reproduce the issue? Perhaps some sample code I could clone and try myself? I've never used the bower-webpack-plugin. I would expect someone who's using webpack to just install dependencies from NPM.

**Comment by deini** [comment]
I'm using it with bower + webpack + bower-webpack-plugin with no problems, I just use one chunk tho but I don't think that would be related.

**Comment by jmdobry** [comment]
@deini If you're willing and have a moment, perhaps you could share a simplified version of your setup? Thanks either way.
