### ISSUE TITLE
Is there a TypeScript def file?

### ISSUE THREAD

**Issue by dougarp** [jmdobry/angular-cache#221]
Hi - I'm in the process of integrating TypeScript into one of our Angular apps - which uses angular-cache of course - and I noticed there's no TypeScript def file.   Any plans on publishing one?   Or maybe you know of a way around it?  (I'm a TypeScript noob, btw).

Thanks in advance...

**Comment by jmdobry** [comment]
I'm a TypeScript noob too, and no TypeScript def file that I know of. I'd happily merge the PR if someone wanted to contribute one.

**Comment by jmdobry** [comment]
There is now a TypeScript definition file: https://github.com/jmdobry/CacheFactory/blob/master/dist/cachefactory.d.ts
