### ISSUE TITLE
Can use with Angular 2? any other recommendations?

### ISSUE THREAD

**Issue by chauey** [jmdobry/angular-cache#222]
Hello there, I was curious what are some of the best solutions for caching in Angular 2? This and/or others? Thanks

**Comment by naivefun** [comment]
+1

**Comment by Jacke** [comment]
For now you can use https://github.com/jmdobry/CacheFactory core and inject in to your angular app, this is good practice, we already do it for restangular replacement and other strictly dependent libs

**Comment by jmdobry** [comment]
I'll repeat what @Jacke said: Use [CacheFactory](https://github.com/jmdobry/CacheFactory) with Angular 2.
