### ISSUE TITLE
Is there a possibility that angular-cache's clearAll method effects other parts of local storage

### ISSUE THREAD

**Issue by BioPhoton** [jmdobry/angular-cache#227]
As far as i see in the code there is no possibility that the clearAll methods effect other parts of the local storage.
This issue is just a question to be sure that i didn't over look something.

**Comment by jmdobry** [comment]
You are correct. Angular-cache will never delete anything from localStorage that it didn't put there itself.

**Comment by BioPhoton** [comment]
THX
