### ISSUE TITLE
Rename CacheFactory

### ISSUE THREAD

**Issue by blckshrk** [jmdobry/angular-cache#228]
Hi,

As recommended by Douglas Crockford in "JavaScript: The Good Parts", only constructor functions should be start with an upper case. `CacheFactory` is a function, but do not need a `new`, it could be confusing in some situations to name it in PascalCase.

May be `CacheFactory` could be renamed to `$angularCache` or something else ? We could also easily keep `CacheFactory` for backward compatibility.

What do you think about it ?

Alex

**Comment by jmdobry** [comment]
`CacheFactory` only works as a function for backwards compatibility. You should use `CacheFactory#createCache(name, [options])` instead.

**Comment by blckshrk** [comment]
Right, that makes sense! In this case the documentation should be updated, because all the examples are based on this. Maybe this is already in the roadmap ? I could do it if needed.

**Comment by jmdobry** [comment]
A pull request would be great

**Comment by jmdobry** [comment]
As of CacheFactory v2.0.0 the only way to create a cache is to do the following:

```js
import CacheFactory from 'cachefactory';

const cacheFactory = new CacheFactory();
const cache = cacheFactory.createCache('my-cache');
```
