### ISSUE TITLE
Wildcard support when remove operations

### ISSUE THREAD

**Issue by krystalcode** [jmdobry/angular-cache#231]
I am caching certain API calls and I use the provided parameters in the cache key because the response depends on them. It would be useful to be able to clear all related entries using a wildcard.

```
// Cache response from the same endpoint.
cache.put('endpoint/{param1:value1,param2:value2}', response);
cache.put('endpoint/{param3:value3}', response);

// Remove all cached responses for this endpoint.
cache.remove('/endpoint/*');
```

This does not seem to work at the moment. Is it possible to support it?

**Comment by jmdobry** [comment]
Not really, angular-cache and `$cacheFactory` and `localStorage` are key-value stores. They don't support collection-based queries. For that I would recommend something like [js-data.io](http://js-data.io)

**Comment by krystalcode** [comment]
Ok thanks for the response. I'll have a look at another solution, js-data looks great. Meanwhile, until I have time to migrate, I can think of two solutions.

1. Use caches as collections. At the moment I define 2-3 caches based on expiration time e.g. 1 cache for items that should expire daily, 1 for items that should expire every minute etc. I could add a few extra caches that would correspond to collections, so that I can remove all items using cache.destroy(). There may be about 10 such extra caches.

2. Maintain a list of the keys in a separate cache entry, and remove all of them one by one when desired.

The 1st approach seems to be the easiest and most performant, since the 2nd will have an extra overhead for both 'put' and 'remove' operations. Not knowing the internals of this library, is there any disadvantage of the 1st approach?

**Comment by jmdobry** [comment]
In your code, just do something like this:

```js
function removeKeys (cache, pattern) {
  return cache.keys().map((key) => {
    if (pattern.test(key)) {
      return {
        key: key,
        value: cache.remove(key)
      };
    }
  }).filter((x) => x);
}

const removedKeyValuePairs = removeKeys(myCache, /some-endpoint\/.*/);
```

**Comment by krystalcode** [comment]
Sounds good, thanks.
