### ISSUE TITLE
I want to use storageMode memory and localStorage both

### ISSUE THREAD

**Issue by yogeshgadge** [jmdobry/angular-cache#248]
Can this be done ?

**Comment by yogeshgadge** [comment]
#

**Comment by AnthonyCC** [comment]
is there a valid use case to store the same data in both localStorage and memory?

**Comment by merqlove** [comment]
Use it as different services... Or in single service but with 2 cache objects... Hard to imagine your use case,,,

**Comment by jmdobry** [comment]
The current implementation does not support this.
