### ISSUE TITLE
Does Angular-cache have any size/capacity/quota limits

### ISSUE THREAD

**Issue by KHA-Koby** [jmdobry/angular-cache#253]
I am currently using SessionStorage for my caching but for some larger data-sets I get a message:

> 'Setting the value of 'xyz' exceeded the quota.'

 will I encounter the same issues when I convert to angular-cache? what are the quota limitations?

**Comment by jmdobry** [comment]
angular-cache itself does not impose any limits. However, various browsers have different size limits for `localStorage`. See #180
