### ISSUE TITLE
Unknown provider: CacheFactory on app.config()

### ISSUE THREAD

**Issue by localh0rzd** [jmdobry/angular-cache#255]
I'm trying to set up angular-cache 4.6.0 with an angular 1.5.8 project. 

`var module = angular.module('client', [
        'angular-cache',
       /* other modules */
    ]);`

Inside the app.js, I call module.config() several times (with `$logProvider`, `$httpProvider` and others), e.g.:
```
    module.config(['$logProvider', function ($logProvider) {
        $logProvider.debugEnabled(true);
    }]);
    module.config(['$httpProvider', function ($httpProvider){
        $httpProvider.defaults.cache = true;
        $httpProvider.interceptors.push(/* ... */);
    }]);
```

The call `    module.config(['CacheFactory', function (CacheFactoryProvider) {
        /* ... */
    }]);` however fails with `Unknown provider: CacheFactory`

The angular-cache.js comes right after angular.js inside the HTML.

What can possibly cause this issue?

**EDIT**: Nevermind, I just discovered one has to add "Provider" to a provider name inside .config()...
Issue can be closed.

**Comment by delagen** [comment]
@localh0rzd can you close this?
